front_user:
    resource: "@FrontBundle/Controller/Backend/UserController.php"
    type:     annotation

front:
    resource: "@FrontBundle/Controller/Frontend"
    type:     annotation

default:
    resource: "@FrontBundle/Controller"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

iotsmartfitbit:
    type:     annotation
    resource: "@iotsmartfitbitBundle/Controller"
    prefix:   /import/module/fitbit

iotsmart_hue:
    type:     annotation
    resource: "@iotsmartHueBundle/Controller"
    prefix:   /import/module/hue

#REST
api :
    type : rest
    resource : "@ApiBundle/Resources/config/routing_rest.yml"
    prefix: /api

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
